spring.application.name=bank-project

spring.datasource.url= jdbc:postgresql://localhost:5432/BankDB
spring.datasource.username=postgres
spring.datasource.password=rachit21

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

#This is add as root end point in our path
server.servlet.context-path=/api


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.web=DEBUG